# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eafd8e8001ad82e2fe30179ca69277d8ad751435e3606215aa451ef4302da17fad0ec825059deb744b17c95a4c92b5db92fb4e9c7b6ce23bf743c1606639111e

test:
  secret_key_base: 31b0d7fb94dd7b8b7737dbd70824686539c7da63407b0a242273436949c834c401180ee1c5944e67e0a92f68bcb01f908a3ba356918c8b8c079fbc6591f82fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
